spring:
    redis:
      host: localhost        # Redis服务器地址
      port: 6379               # Redis服务器连接端口
      password:                # Redis服务器连接密码（默认为空）      
      database: 0              # Redis数据库索引（默认为0）
      jedis:
        pool:
          max-active: 8        # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1         # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 500        # 连接池中的最大空闲连接
          min-idle: 0          # 连接池中的最小空闲连接
      lettuce:
        shutdown-timeout: 0
#微信支付配置类
ly:  
  pay:    
    wx:      
      appID: wx8397f8696b538317  #公众号id      
      mchID: 1473426802  #商户号id      
      key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb  # 秘钥      
      notifyurl: http://a31ef7db.ngrok.io/WeChatPay/WeChatPayNotify  #回调地址